# Generated by Django 4.0.4 on 2022-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devyatki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateentry',
            name='telegram_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
